export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_REQUEST_SUCCESS = "BOOKS_REQUEST_SUCCESS";
export const BOOKS_REQUEST_FAIL = "BOOKS_REQUEST_FAIL";

export const BOOKS_DETAILS_REQUEST = "BOOKS_DETAILS_REQUEST";
export const BOOKS_DETAILS_SUCCESS = "BOOKS_DETAILS_SUCCESS";
export const BOOKS_DETAILS_FAIL = "BOOKS_DETAILS_FAIL";

export const OLD_BOOKS_REQUEST = "OLD_BOOKS_REQUEST";
export const OLD_BOOKS_REQUEST_SUCCESS = "OLD_BOOKS_REQUEST_SUCCESS";
export const OLD_BOOKS_REQUEST_FAIL = "OLD_BOOKS_REQUEST_FAIL";

export const OLD_BOOKS_DEATILS = "OLD_BOOKS_DEATILS";
export const OLD_BOOKS_DEATILS_SUCCESS = "OLD_BOOKS_DEATILS_SUCCESS";
export const OLD_BOOKS_DEATILS_FAIL = "OLD_BOOKS_DEATILS_FAIL";

export const USER_BOOKS_DEATILS = "USER_BOOKS_DEATILS";
export const USER_BOOKS_DEATILS_SUCCESS = "USER_BOOKS_DEATILS_SUCCESS";
export const USER_BOOKS_DEATILS_FAIL = "USER_BOOKS_DEATILS_FAIL";

export const SIMILAR_BOOKS_DEATILS = "SIMILAR_BOOKS_DEATILS";
export const SIMILAR_BOOKS_DEATILS_SUCCESS = "SIMILAR_BOOKS_DEATILS_SUCCESS";
export const SIMILAR_BOOKS_DEATILS_FAIL = "SIMILAR_BOOKS_DEATILS_FAIL";

export const UPLOAD_BOOKS_DEATILS = "UPLOAD_BOOKS_DEATILS";
export const UPLOAD_BOOKS_DEATILS_SUCCESS = "UPLOAD_BOOKS_DEATILS_SUCCESS";
export const UPLOAD_BOOKS_DEATILS_FAIL = "UPLOAD_BOOKS_DEATILS_FAIL";
export const UPLOAD_BOOKS_DEATILS_REST = "UPLOAD_BOOKS_DEATILS_REST";

export const BOOKS_EMAIL_REQUEST = "BOOKS_EMAIL_REQUEST";
export const BOOKS_EMAIL_SUCCESS = "BOOKS_EMAIL_SUCCESS";
export const BOOKS_EMAIL_FAIL =  "BOOKS_EMAIL_FAIL";
export const BOOKS_EMAIL_REST =  "BOOKS_EMAIL_REST";

export const DELETE_BOOKS_DEATILS = "DELETE_BOOKS_DEATILS";
export const DELETE_BOOKS_DEATILS_SUCCESS = "DELETE_BOOKS_DEATILS_SUCCESS";
export const DELETE_BOOKS_DEATILS_FAIL = "DELETE_BOOKS_DEATILS_FAIL";
export const DELETE_BOOKS_DEATILS_REST = "DELETE_BOOKS_DEATILS_REST";